<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $catalogs = array(
            array('cat_number' => '1', 'parent_cat' => '0', 'cat_name_en' => 'Equipment', 'cat_type' => 0),
            array('cat_number' => '2', 'parent_cat' => '0', 'cat_name_en' => 'Parts', 'cat_type' => 1),
            array('cat_number' => '1.1', 'parent_cat' => '1', 'cat_name_en' => 'Brand', 'cat_type' => 0),
            array('cat_number' => '1.1.1', 'parent_cat' => '1.1', 'cat_name_en' => 'BELARUS90/92', 'cat_type' => 0),
            array('cat_number' => '2.1', 'parent_cat' => '2', 'cat_name_en' => 'Brand', 'cat_type' => 1),
            array('cat_number' => '2.1.1', 'parent_cat' => '2.1', 'cat_name_en' => 'BELARUS90/92', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Diesel mechanisms', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.1', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Drive and counter installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.2', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Cylinder head and intake line installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.3', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Cylinder head and intake line installation for engines D-244', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.4', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Pistons and connecting rods. Crankshaft. Flywheel', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.5', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Clutch coupling installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.6', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Distributing gear', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.7', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Exhaust manifold installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.8', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Oil crankcase installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.10.9', 'parent_cat' => '2.1.1.10', 'cat_name_en' => 'Gear-type pump installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Feed system', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.10', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Air cleaner installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.11', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Fuel equipment installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.12', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Fine fuel filter', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.13', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Coarse fuel filter', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.111', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Fuel Tank', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.112', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Fuel Supply Control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.11.113', 'parent_cat' => '2.1.1.11', 'cat_name_en' => 'Diesel Stop. Emergency Diesel Stop', 'cat_type' => 1),
            array('cat_number' => '2.1.1.12', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Exhaust system', 'cat_type' => 1),
            array('cat_number' => '2.1.1.12.121', 'parent_cat' => '2.1.1.12', 'cat_name_en' => 'Muffler', 'cat_type' => 1),
            array('cat_number' => '2.1.1.13', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Cooling system', 'cat_type' => 1),
            array('cat_number' => '2.1.1.13.14', 'parent_cat' => '2.1.1.13', 'cat_name_en' => 'Thermostat housing installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.13.15', 'parent_cat' => '2.1.1.13', 'cat_name_en' => 'Fan installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.13.131', 'parent_cat' => '2.1.1.13', 'cat_name_en' => 'Water Radiator. Water Radiator Suspension', 'cat_type' => 1),
            array('cat_number' => '2.1.1.13.132', 'parent_cat' => '2.1.1.13', 'cat_name_en' => 'Fan guard (optional)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.14', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Lubrication system', 'cat_type' => 1),
            array('cat_number' => '2.1.1.14.16', 'parent_cat' => '2.1.1.14', 'cat_name_en' => 'Oil pump installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.14.17', 'parent_cat' => '2.1.1.14', 'cat_name_en' => 'Centrifugal filter installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.14.141', 'parent_cat' => '2.1.1.14', 'cat_name_en' => 'Oil cooler', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Clutch', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.161', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Clutch disks', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.162', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Clutch housing', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.163', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Coupling housing (release yoke)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.164', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Clutch housing (Power Take Off drive, Pump Drive of Hydraulic Lift System)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.165', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Clutch housing (reducing gear)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.16.166', 'parent_cat' => '2.1.1.16', 'cat_name_en' => 'Clutch control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Gearbox', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.171', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Gearbox. Gearbox casing', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.172', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Main Drive Shaft. Main Shaft', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.173', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Inner Shaft. Idler Shaft', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.174', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'First gear and reverse Shaft', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.175', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Reducer', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.176', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Gear box with shift lever in the center (designation and short description)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.17.177', 'parent_cat' => '2.1.1.17', 'cat_name_en' => 'Reducer control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.18', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Transfer box', 'cat_type' => 1),
            array('cat_number' => '2.1.1.18.181', 'parent_cat' => '2.1.1.18', 'cat_name_en' => 'Transfer box of front driving axle drive (for Belarus-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.22', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Cardan drive', 'cat_type' => 1),
            array('cat_number' => '2.1.1.22.221', 'parent_cat' => '2.1.1.22', 'cat_name_en' => 'Cardan shaft. Cardan shaft intermediate bearing (for Belarus-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.22.222', 'parent_cat' => '2.1.1.22', 'cat_name_en' => 'Cardan shaft guard (for Belarus-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.23', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Front driving axle', 'cat_type' => 1),
            array('cat_number' => '2.1.1.23.231', 'parent_cat' => '2.1.1.23', 'cat_name_en' => 'Front driving axle assembly. Body and cover. Differential gear. (For Belarus-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.23.232', 'parent_cat' => '2.1.1.23', 'cat_name_en' => 'Main gear. (For the BELARUS-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.23.233', 'parent_cat' => '2.1.1.23', 'cat_name_en' => 'FDA Final Drive Reducing Gear (bevel gear speed reducer).(For the BELARUS-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.24', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Rear axle', 'cat_type' => 1),
            array('cat_number' => '2.1.1.24.241', 'parent_cat' => '2.1.1.24', 'cat_name_en' => 'Rear Axle Body. Final Drive', 'cat_type' => 1),
            array('cat_number' => '2.1.1.24.242', 'parent_cat' => '2.1.1.24', 'cat_name_en' => 'Differential Gear. Bearing Cage', 'cat_type' => 1),
            array('cat_number' => '2.1.1.24.243', 'parent_cat' => '2.1.1.24', 'cat_name_en' => 'Differential Lock', 'cat_type' => 1),
            array('cat_number' => '2.1.1.28', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Frame', 'cat_type' => 1),
            array('cat_number' => '2.1.1.28.281', 'parent_cat' => '2.1.1.28', 'cat_name_en' => 'Semi-Frame', 'cat_type' => 1),
            array('cat_number' => '2.1.1.28.282', 'parent_cat' => '2.1.1.28', 'cat_name_en' => 'Frame', 'cat_type' => 1),
            array('cat_number' => '2.1.1.30', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Front axle group', 'cat_type' => 1),
            array('cat_number' => '2.1.1.30.301', 'parent_cat' => '2.1.1.30', 'cat_name_en' => 'Front Axle and Steering Link (for the BELARUS-90)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.31', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Wheels and hubs', 'cat_type' => 1),
            array('cat_number' => '2.1.1.31.311', 'parent_cat' => '2.1.1.31', 'cat_name_en' => 'Front Driving Wheels. Front Wheel Hubs. (For the BELARUS-90)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.31.312', 'parent_cat' => '2.1.1.31', 'cat_name_en' => 'Front Driving Wheels (for the BELARUS-92)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.31.313', 'parent_cat' => '2.1.1.31', 'cat_name_en' => 'Rear Wheels. Rear Wheel Hubs', 'cat_type' => 1),
            array('cat_number' => '2.1.1.31.314', 'parent_cat' => '2.1.1.31', 'cat_name_en' => 'Spacer (for doubling of rear wheels)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.34', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Steering', 'cat_type' => 1),
            array('cat_number' => '2.1.1.34.341', 'parent_cat' => '2.1.1.34', 'cat_name_en' => 'Steering Drive', 'cat_type' => 1),
            array('cat_number' => '2.1.1.34.342', 'parent_cat' => '2.1.1.34', 'cat_name_en' => 'Hydraulic Units and Steering Booster Fittings', 'cat_type' => 1),
            array('cat_number' => '2.1.1.34.343', 'parent_cat' => '2.1.1.34', 'cat_name_en' => 'Steering Booster Cylinder', 'cat_type' => 1),
            array('cat_number' => '2.1.1.34.344', 'parent_cat' => '2.1.1.34', 'cat_name_en' => 'Control Valve of Steering Booster', 'cat_type' => 1),
            array('cat_number' => '2.1.1.35', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Pneumatic compressor', 'cat_type' => 1),
            array('cat_number' => '2.1.1.35.18', 'parent_cat' => '2.1.1.35', 'cat_name_en' => 'Pneumatic compressor installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.35.351', 'parent_cat' => '2.1.1.35', 'cat_name_en' => 'Service Brakes. Brake Control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.35.352', 'parent_cat' => '2.1.1.35', 'cat_name_en' => 'Parking Brake', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Electric equipment', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.19', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Alternator installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.20', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Starter installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.371', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Engine Electrical Equipment', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.372', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Cab Electrical Equipment', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.373', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Storage Battery Installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.374', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Front Lamp Installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.375', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Working Headlight and Back Lamp Installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.37.376', 'parent_cat' => '2.1.1.37', 'cat_name_en' => 'Socket and License Plate Lamp Installation', 'cat_type' => 1),
            array('cat_number' => '2.1.1.38', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Instruments', 'cat_type' => 1),
            array('cat_number' => '2.1.1.38.381', 'parent_cat' => '2.1.1.38', 'cat_name_en' => 'Dashboard', 'cat_type' => 1),
            array('cat_number' => '2.1.1.39', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Tools and accessories', 'cat_type' => 1),
            array('cat_number' => '2.1.1.39.391', 'parent_cat' => '2.1.1.39', 'cat_name_en' => 'Operator’s Tools', 'cat_type' => 1),
            array('cat_number' => '2.1.1.39.392', 'parent_cat' => '2.1.1.39', 'cat_name_en' => 'First Aid Kit', 'cat_type' => 1),
            array('cat_number' => '2.1.1.39.393', 'parent_cat' => '2.1.1.39', 'cat_name_en' => 'Tool box', 'cat_type' => 1),
            array('cat_number' => '2.1.1.42', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Power takeoff', 'cat_type' => 1),
            array('cat_number' => '2.1.1.42.421', 'parent_cat' => '2.1.1.42', 'cat_name_en' => 'Rear Power Takeoff Shaft (PTO Shaft)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.42.422', 'parent_cat' => '2.1.1.42', 'cat_name_en' => 'Power Pulley', 'cat_type' => 1),
            array('cat_number' => '2.1.1.42.423', 'parent_cat' => '2.1.1.42', 'cat_name_en' => 'PTO shaft control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.42.424', 'parent_cat' => '2.1.1.42', 'cat_name_en' => 'Front Ballast Weight', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Hydraulic lift linkage', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.461', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Rear Mounting Mechanism', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.463', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Hydraulic Unit Control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.464', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Fittings of Hydraulic Unit Housing', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.465', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Hydraulic Units and Fittings', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.466', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Housing of Hydraulic Units, Filter and Hydraulic Pump Drive', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.467', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Hydraulic Cylinder C 100x200', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.468', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Distributor R80-3/1-222-ЗGg', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.469', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Locking Device', 'cat_type' => 1),
            array('cat_number' => '2.1.1.46.4610', 'parent_cat' => '2.1.1.46', 'cat_name_en' => 'Retention Mechanism', 'cat_type' => 1),
            array('cat_number' => '2.1.1.48', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Rear axle differential-lock control and fittings', 'cat_type' => 1),
            array('cat_number' => '2.1.1.48.481', 'parent_cat' => '2.1.1.48', 'cat_name_en' => 'Differential-lock Sensor. Fittings of Locking Sensor', 'cat_type' => 1),
            array('cat_number' => '2.1.1.48.482', 'parent_cat' => '2.1.1.48', 'cat_name_en' => 'Differential Lock Control', 'cat_type' => 1),
            array('cat_number' => '2.1.1.67', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Tractor cab', 'cat_type' => 1),
            array('cat_number' => '2.1.1.67.671', 'parent_cat' => '2.1.1.67', 'cat_name_en' => 'Cab (canopy frame)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.67.672', 'parent_cat' => '2.1.1.67', 'cat_name_en' => 'Cab (canopy frame)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.68', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Seat', 'cat_type' => 1),
            array('cat_number' => '2.1.1.68.681', 'parent_cat' => '2.1.1.68', 'cat_name_en' => 'Operator’s Seat', 'cat_type' => 1),
            array('cat_number' => '2.1.1.68.682', 'parent_cat' => '2.1.1.68', 'cat_name_en' => 'Seat. Adjusting Mechanism', 'cat_type' => 1),
            array('cat_number' => '2.1.1.82', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Cab accessories', 'cat_type' => 1),
            array('cat_number' => '2.1.1.82.821', 'parent_cat' => '2.1.1.82', 'cat_name_en' => 'Sun Visor', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84', 'parent_cat' => '2.1.1', 'cat_name_en' => 'Empennage', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84.841', 'parent_cat' => '2.1.1.84', 'cat_name_en' => 'Grille. Hood', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84.842', 'parent_cat' => '2.1.1.84', 'cat_name_en' => 'Front Fenders', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84.843', 'parent_cat' => '2.1.1.84', 'cat_name_en' => 'Front Fenders (version)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84.844', 'parent_cat' => '2.1.1.84', 'cat_name_en' => 'Front Fenders (version)', 'cat_type' => 1),
            array('cat_number' => '2.1.1.84.845', 'parent_cat' => '2.1.1.84', 'cat_name_en' => 'Foot Board', 'cat_type' => 1),
        );

        foreach($catalogs as $catalog) {
            DB::table('catalog')->insert([
                'cat_number' => $catalog['cat_number'],
                'parent_cat' => $catalog['parent_cat'],
                'cat_type' => $catalog['cat_type'],
                'cat_name_en' => $catalog['cat_name_en'],
                'cat_name_ar' => $catalog['cat_name_en'],
                'created_at' => Carbon::now(),
            ]);
        }
    }
}
