@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="page-title">{{ $pageTitle }}</h1>
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cumque, dolores ducimus eos facere fuga, harum itaque iure molestiae necessitatibus nemo nisi numquam perspiciatis repellat sint tempora tempore, unde veniam!</span><span>Aperiam corporis dolor dolorem error est fugit laboriosam natus necessitatibus non numquam, obcaecati, perferendis provident quis quo quod recusandae sapiente? Eius, eos excepturi fugit molestias natus officiis optio pariatur rerum.</span><span>Ab adipisci animi architecto at autem culpa deleniti deserunt eos facere fugit iusto laborum, natus nemo odio perspiciatis praesentium provident quas qui quibusdam quod recusandae sapiente unde ut voluptas voluptatibus.</span></p>
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cumque, dolores ducimus eos facere fuga, harum itaque iure molestiae necessitatibus nemo nisi numquam perspiciatis repellat sint tempora tempore, unde veniam!</span><span>Aperiam corporis dolor dolorem error est fugit laboriosam natus necessitatibus non numquam, obcaecati, perferendis provident quis quo quod recusandae sapiente? Eius, eos excepturi fugit molestias natus officiis optio pariatur rerum.</span><span>Ab adipisci animi architecto at autem culpa deleniti deserunt eos facere fugit iusto laborum, natus nemo odio perspiciatis praesentium provident quas qui quibusdam quod recusandae sapiente unde ut voluptas voluptatibus.</span></p>
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cumque, dolores ducimus eos facere fuga, harum itaque iure molestiae necessitatibus nemo nisi numquam perspiciatis repellat sint tempora tempore, unde veniam!</span><span>Aperiam corporis dolor dolorem error est fugit laboriosam natus necessitatibus non numquam, obcaecati, perferendis provident quis quo quod recusandae sapiente? Eius, eos excepturi fugit molestias natus officiis optio pariatur rerum.</span><span>Ab adipisci animi architecto at autem culpa deleniti deserunt eos facere fugit iusto laborum, natus nemo odio perspiciatis praesentium provident quas qui quibusdam quod recusandae sapiente unde ut voluptas voluptatibus.</span></p>
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cumque, dolores ducimus eos facere fuga, harum itaque iure molestiae necessitatibus nemo nisi numquam perspiciatis repellat sint tempora tempore, unde veniam!</span><span>Aperiam corporis dolor dolorem error est fugit laboriosam natus necessitatibus non numquam, obcaecati, perferendis provident quis quo quod recusandae sapiente? Eius, eos excepturi fugit molestias natus officiis optio pariatur rerum.</span><span>Ab adipisci animi architecto at autem culpa deleniti deserunt eos facere fugit iusto laborum, natus nemo odio perspiciatis praesentium provident quas qui quibusdam quod recusandae sapiente unde ut voluptas voluptatibus.</span></p>
    </div>
    <!-- /.container -->
@endsection
